[package]
name = "fast_count"
version = "0.1.0"
authors = ["arodic"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
